# docker-compose.yml

version: '3.8'

services:
  socialsync:
    build: .
    container_name: socialsync-app
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./downloads:/app/downloads
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    networks:
      - socialsync-network

  nginx:
    image: nginx:alpine
    container_name: socialsync-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - socialsync
    networks:
      - socialsync-network

networks:
  socialsync-network:
    driver: bridge